/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.forms;

import dbhandler.dao.UserModel;
import entities.Convocatory;
import entities.Municipios;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Mauro
 */
public class ApplicantForm extends javax.swing.JFrame {

    /**
     * Creates new form ApplicantForm
     */
    public ApplicantForm(int idconvocatory) {
        try {
            initComponents();
            loadcombox();
        } catch (SQLException ex) {
            System.out.println("Error al cargar conbox de Applicant");
        }
    }
    
        public void close() {
        this.setVisible(false);
        this.dispose();
    }

    public void loadcombox() throws SQLException {
        UserModel usermodel = new UserModel();
        String string = new String();

        Vector<Municipios> arrayconvocatory = usermodel.readMunicipios();

        for (Municipios arraymunicipios1 : arrayconvocatory) {
            string = arraymunicipios1.getNamemunicipio();
            CbMunicipios.addItem(string);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitle = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        lbnombre = new javax.swing.JLabel();
        tflastname = new javax.swing.JTextField();
        lblastname = new javax.swing.JLabel();
        tfidentification = new javax.swing.JTextField();
        lbidentification = new javax.swing.JLabel();
        tfStreetaddress = new javax.swing.JTextField();
        lbStreetaddress = new javax.swing.JLabel();
        tfinstitution = new javax.swing.JTextField();
        lbinstitution = new javax.swing.JLabel();
        CbMunicipios = new javax.swing.JComboBox();
        lbmunicipio = new javax.swing.JLabel();
        btsave = new javax.swing.JButton();
        btclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos Personales");

        lbtitle.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbtitle.setText("Datos Personales");

        tfNombre.setToolTipText("");
        tfNombre.setName("Nombre"); // NOI18N
        tfNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNombreActionPerformed(evt);
            }
        });

        lbnombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbnombre.setText("Nombre:");

        tflastname.setToolTipText("");
        tflastname.setName("Nombre"); // NOI18N
        tflastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tflastnameActionPerformed(evt);
            }
        });

        lblastname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblastname.setText("Apellido:");

        tfidentification.setToolTipText("");
        tfidentification.setName("Nombre"); // NOI18N
        tfidentification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfidentificationActionPerformed(evt);
            }
        });

        lbidentification.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbidentification.setText("Cedula:");

        tfStreetaddress.setToolTipText("");
        tfStreetaddress.setName("Nombre"); // NOI18N
        tfStreetaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStreetaddressActionPerformed(evt);
            }
        });

        lbStreetaddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbStreetaddress.setText("Direccion de residencia:");

        tfinstitution.setToolTipText("");
        tfinstitution.setName("Nombre"); // NOI18N
        tfinstitution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfinstitutionActionPerformed(evt);
            }
        });

        lbinstitution.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbinstitution.setText("Intitucion donde proviene:");

        CbMunicipios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        lbmunicipio.setText("Municipio de procedencia:");

        btsave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btsave.setText("Guardar");
        btsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaveActionPerformed(evt);
            }
        });

        btclose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btclose.setText("Cancelar");
        btclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(tfNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblastname, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tflastname))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbidentification, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfidentification))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbmunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CbMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbinstitution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbStreetaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfStreetaddress))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(tfinstitution))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(btsave, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btclose, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(lbtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblastname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(tflastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbidentification, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(tfidentification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbStreetaddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(tfStreetaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbinstitution, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))
                    .addComponent(tfinstitution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbMunicipios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbmunicipio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btsave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btclose, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNombreActionPerformed

    private void tflastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tflastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tflastnameActionPerformed

    private void tfidentificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfidentificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfidentificationActionPerformed

    private void tfStreetaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStreetaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStreetaddressActionPerformed

    private void tfinstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfinstitutionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfinstitutionActionPerformed

    private void btcloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcloseActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btcloseActionPerformed

    private void btsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaveActionPerformed
        // TODO add your handling code here:
        
        JOptionPane.showMessageDialog(this,"Se ha guardado con exito","Guardado",1);
    }//GEN-LAST:event_btsaveActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbMunicipios;
    private javax.swing.JButton btclose;
    private javax.swing.JButton btsave;
    private javax.swing.JLabel lbStreetaddress;
    private javax.swing.JLabel lbidentification;
    private javax.swing.JLabel lbinstitution;
    private javax.swing.JLabel lblastname;
    private javax.swing.JLabel lbmunicipio;
    private javax.swing.JLabel lbnombre;
    private javax.swing.JLabel lbtitle;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfStreetaddress;
    private javax.swing.JTextField tfidentification;
    private javax.swing.JTextField tfinstitution;
    private javax.swing.JTextField tflastname;
    // End of variables declaration//GEN-END:variables
}
