/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.forms;

import resources.R;
import entities.Convocatory;
import dbhandler.dao.UserModel;
import java.sql.SQLException;
import java.sql.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import resources.Exceptionform;

/**
 *
 * @author Mauro
 */
public class CreateConvocatoryForm extends javax.swing.JFrame {

    /**
     * Creates new form CreateConvocatoryForm
     */
    public Exceptionform exeptiones = new Exceptionform("Crear convocatoria");

    public CreateConvocatoryForm() {
        initComponents();
        /*Modifico los elementos de la interface para asociarlos a la clase R*/

        lbtitle.setText(R.STR_NEW_CONVOCATORY);
        lbdatestart.setText(R.STR_START_DATE + ":");
        lbdateend.setText(R.STR_END_DATE + ":");
        lbdescription.setText(R.STR_DESCRIPTION_CONVOCATORY);
        /*Control de la ventana*/
        this.setIconImage(R.ICON_CONVOCATORY_SMALL.getImage());
        this.setTitle(R.STR_TITLE_CONVOCATORY);

        lbico.setIcon(R.ICON_CONVOCATORY);
        lbnameconvocatory.setText(R.STR_NAME_CONVOCATORY);
        tfnameconvocatory.setText("");
        lbdatepublish.setText(R.STR_DATE_PUBLIC);

        btexit.setText(R.STR_CANCEL);
        btnewconvocatory.setText(R.STR_ADD);

    }

    public void close() {
        this.setVisible(false);
        this.dispose();
    }

    public void clear() {
        taDescription.setText("");
        tfnameconvocatory.setText("");
        dtend.setDate(null);
        dtpublicher.setDate(null);
        dtstart.setDate(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbtitle = new javax.swing.JLabel();
        dtend = new com.toedter.calendar.JDateChooser();
        dtstart = new com.toedter.calendar.JDateChooser();
        btnewconvocatory = new javax.swing.JButton();
        btexit = new javax.swing.JButton();
        lbdatestart = new javax.swing.JLabel();
        lbdateend = new javax.swing.JLabel();
        lbico = new javax.swing.JLabel();
        lbnameconvocatory = new javax.swing.JLabel();
        tfnameconvocatory = new javax.swing.JTextField();
        lbdatepublish = new javax.swing.JLabel();
        dtpublicher = new com.toedter.calendar.JDateChooser();
        lbdescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbtitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbtitle.setText("Titulo");

        dtend.setName("clistart"); // NOI18N

        dtstart.setName("clistart"); // NOI18N

        btnewconvocatory.setText("Crear");
        btnewconvocatory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnewconvocatoryActionPerformed(evt);
            }
        });

        btexit.setText("Cancelar");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        lbdatestart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdatestart.setText("Inicio");

        lbdateend.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdateend.setText("Fecha de finalizacion");

        lbnameconvocatory.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbnameconvocatory.setText("name");

        tfnameconvocatory.setText("nombre");
        tfnameconvocatory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnameconvocatoryActionPerformed(evt);
            }
        });

        lbdatepublish.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdatepublish.setText("Fecha de publicavion");

        lbdescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbdescription.setText("descripcion");

        taDescription.setColumns(20);
        taDescription.setRows(5);
        jScrollPane1.setViewportView(taDescription);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbdatepublish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(81, 81, 81)
                                .addComponent(btexit)
                                .addGap(18, 18, 18)
                                .addComponent(btnewconvocatory)
                                .addGap(79, 79, 79))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbico, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(90, 90, 90)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbnameconvocatory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfnameconvocatory, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(dtpublicher, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbdateend, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                    .addComponent(lbdatestart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtstart, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dtend, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbdescription, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(106, 106, 106))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbico, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbtitle))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfnameconvocatory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnameconvocatory))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbdatepublish)
                    .addComponent(dtpublicher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dtstart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbdatestart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbdateend)
                    .addComponent(dtend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbdescription)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnewconvocatory)
                    .addComponent(btexit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_btexitActionPerformed

    private void btnewconvocatoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnewconvocatoryActionPerformed
        // TODO add your handling code here: 
        try {
            String stNameconvocatory, stdescription;
            Date stStartdate;
            Date stEnddate;
            Date stPubilcdate;
            stdescription = taDescription.getText();
            stNameconvocatory = tfnameconvocatory.getText();
 /*-_-_-_-Bloque de excepciones*/
            Exceptionform.Fechavacia(dtstart.getDate());
            Exceptionform.Fechavacia(dtend.getDate());
            Exceptionform.Fechavacia(dtpublicher.getDate());
            
            Exceptionform.Fechacorrespondencia(dtend.getDate(),dtstart.getDate());
            Exceptionform.Fechacorrespondencia(dtpublicher.getDate(),dtend.getDate());
            
            Exceptionform.campoVacio(tfnameconvocatory);
 /*_-_-_-_-Fin Bloque Excepciones*/
            stStartdate = new java.sql.Date(dtstart.getDate().getTime());
            stEnddate = new java.sql.Date(dtend.getDate().getTime());
            stPubilcdate = new java.sql.Date(dtpublicher.getDate().getTime());

            

            Convocatory convocatoria = new Convocatory(stNameconvocatory, true, stStartdate, stEnddate, stPubilcdate, stdescription);
            /*Crea convocatoria*/
            UserModel usermodel = new UserModel();
            usermodel.createConvocatory(convocatoria);
            /*mensaje fin de la convocatoria*/
            clear();
            JOptionPane.showMessageDialog(this, R.STR_CONVOCATORY_ADD);
        }
        catch (SQLException ex) {
                System.out.println("Error Sql al guardar la convocatoria " + ex);
                clear();
            }catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_btnewconvocatoryActionPerformed

    private void tfnameconvocatoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnameconvocatoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnameconvocatoryActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btexit;
    private javax.swing.JButton btnewconvocatory;
    private com.toedter.calendar.JDateChooser dtend;
    private com.toedter.calendar.JDateChooser dtpublicher;
    private com.toedter.calendar.JDateChooser dtstart;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbdateend;
    private javax.swing.JLabel lbdatepublish;
    private javax.swing.JLabel lbdatestart;
    private javax.swing.JLabel lbdescription;
    private javax.swing.JLabel lbico;
    private javax.swing.JLabel lbnameconvocatory;
    private javax.swing.JLabel lbtitle;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextField tfnameconvocatory;
    // End of variables declaration//GEN-END:variables
}
