/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.forms;

import dbhandler.dao.UserModel;
import entities.Convocatory;
import entities.User;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;

/**
 *
 * @author Mauro
 */
public class DigitadorForm extends javax.swing.JFrame {

    /**
     * Creates new form DigitadorForm
     */
    public DigitadorForm() {
        initComponents();
    }

    public DigitadorForm(User user) {
        try {
            initComponents();
            lbTitle.setText("Welcome: " + user.getFirstname() + " " + user.getLastname());
            loadcombox(1);
        } catch (SQLException ex) {
            Logger.getLogger(DigitadorForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JButton();
        btForm = new javax.swing.JButton();
        lbTitle = new javax.swing.JLabel();
        cbConvocatory = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel Digitador");

        close.setText("Cerrar Sesion");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        btForm.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btForm.setText("Formulario del Aspirante");
        btForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFormActionPerformed(evt);
            }
        });

        lbTitle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbConvocatory.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cbConvocatory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbConvocatoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(close)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btForm)
                    .addComponent(cbConvocatory, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(close)
                    .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(cbConvocatory, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btForm)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_closeActionPerformed

    private void btFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFormActionPerformed
        int idconvococatory = idselectconvocatory();
        ApplicantForm applicant = new ApplicantForm(idconvococatory);
        applicant.setVisible(true);
                

    }//GEN-LAST:event_btFormActionPerformed

    private void cbConvocatoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbConvocatoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbConvocatoryActionPerformed
    /*Funciones implementadas*/

    public void close() {
        this.setVisible(false);
        this.dispose();
    }

    public void loadcombox(int state) throws SQLException {
        UserModel usermodel = new UserModel();
        String string = new String();

        Vector<Convocatory> arrayconvocatory = usermodel.readConvocatory(state);

        for (Convocatory arrayconvocatory1 : arrayconvocatory) {
            string = arrayconvocatory1.getName_convocatory();
            cbConvocatory.addItem(arrayconvocatory1.getId_convocatory() + ": " + string);
        }
    }

    public int idselectconvocatory() {
        int id = 0;
        String stringid = cbConvocatory.getSelectedItem().toString();
        stringid = stringid.substring(0, stringid.indexOf(":"));
        id = Integer.parseInt(stringid);
        return id;
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btForm;
    private javax.swing.JComboBox cbConvocatory;
    private javax.swing.JButton close;
    private javax.swing.JLabel lbTitle;
    // End of variables declaration//GEN-END:variables
}
